image: alpine:latest

variables:
  AWS_DEFAULT_REGION: us-east-2
  BUCKET_NAME: aws-solutions.tactfulcloud.com
  SOLUTION: workspaces-bastion

stages:
  - deploy

deploy_solution:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync . s3://${BUCKET_NAME}/{SOLUTION} --delete --exclude ".git/*"  --exclude ".gitlab-ci.yml" --exclude "README.md"
  only:
  - master
  only:
    - master
